=== ManhHongPham/semester6_xml/vidu/src/vidu/hoadon.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--- Put your DTDDoc comment here. -->
<!ELEMENT vatlieu (hoadon+|tenhang|soluong|dongia|thanhtien)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hoadon (tenkhach|diachi|chitiet|nguoiban|thoitian|vatlieu)*>
<!ATTLIST hoadon mahd CDATA #REQUIRED >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tenkhach (#PCDATA)>
<!ATTLIST tenkhach gioitinh CDATA #IMPLIED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT diachi (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT chitiet (tenhang|soluong|dongia|thanhtien)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tenhang (#PCDATA)>
<!ATTLIST tenhang mahang CDATA #REQUIRED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT soluong (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dongia (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT thanhtien (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nguoiban (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT thoitian (ngay|thang|nam)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ngay (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT thang (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nam (#PCDATA)>

=== ManhHongPham/semester6_xml/vidu/src/vidu/hoadon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vatlieu SYSTEM 'hoadon.dtd'>
<vatlieu>
    <hoadon mahd="ab1"> 
        <tenkhach gioitinh="nam"> hoang vo van</tenkhach>
        <diachi>hai duong</diachi>
        <vatlieu>
            <tenhang mahang="a12">maytinh</tenhang>
            <soluong>20</soluong>
            <dongia>20000</dongia>
            <thanhtien>400000</thanhtien>
        </vatlieu>
        <nguoiban>hoa</nguoiban>
        <thoitian>
            <ngay>12</ngay>
            <thang>3</thang>
            <nam>2021</nam>
        </thoitian>
    </hoadon>
    <hoadon mahd="ab1">
        <tenkhach> sdf</tenkhach>
        <diachi>hai duong</diachi>
        <vatlieu>
            <tenhang mahang="a12">maytinh</tenhang>
            <soluong>20</soluong>
            <dongia>20000</dongia>
            <thanhtien>400000</thanhtien>
        </vatlieu>
        <vatlieu>
            <tenhang mahang="a12">maytinh</tenhang>
            <soluong>20</soluong>
            <dongia>20000</dongia>
            <thanhtien>400000</thanhtien>
        </vatlieu>
        <vatlieu>
            <tenhang mahang="a12">maytinh</tenhang>
            <soluong>20</soluong>
            <dongia>20000</dongia>
            <thanhtien>400000</thanhtien>
        </vatlieu>
        <nguoiban>hoa</nguoiban>
        <thoitian>
            <ngay>12</ngay>
            <thang>3</thang>
            <nam>2021</nam>
        </thoitian>
    </hoadon>
</vatlieu>
