=== ManhHongPham/semester6_xml/session 1/Proj_5002_xml/src/Section1/Congty.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT congty (nhanvien+)>
<!ELEMENT nhanvien (hoten,dienthoai,luong,thuong,diachi)>
<!ELEMENT hoten (#PCDATA)>
<!ELEMENT dienthoai (#PCDATA)>
<!ELEMENT luong (#PCDATA)>
<!ELEMENT thuong (#PCDATA)>
<!ELEMENT diachi (#PCDATA)>
<!ATTLIST nhanvien manv CDATA #REQUIRED>
<!ATTLIST nhanvien gioitinh (nam|nu) "nam">

<!ENTITY hn "Ha noi">
<!ENTITY hp "Hai phong">
<!-- <!ATTLIST nhanvien manv CDATA #IMPLIED>
<!ATTLIST nhanvien manv CDATA "">
 -->

=== ManhHongPham/semester6_xml/session 1/Proj_5002_xml/src/Section1/Congty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE congty SYSTEM 'Congty.dtd'>
<congty>
    <nhanvien manv="m1" gioitinh="nam">
        <hoten>Nguyen Thi Anh</hoten>
        <dienthoai>9876453454</dienthoai>
        <luong>2000000</luong>
        <thuong>300000</thuong>  
        <diachi>&lt;Ha noi &gt;</diachi>      
    </nhanvien>
    <nhanvien manv="m2" gioitinh="nam">
        <hoten>Phan Van Tuan</hoten>
        <dienthoai>8765987656</dienthoai>
        <luong>3000000</luong>
        <thuong>200000</thuong>    
        <diachi>&hp;</diachi>    
    </nhanvien>
</congty>
