=== ManhHongPham/semester6_xml/session 1/Proj_5002_xml/src/Section1/Lophoc.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lophoc (sinhvien)+>      

<!-- tu 1->n -->
<!-- * tu 0->n ->
<!--- Put your DTDDoc comment here. -->
<!ELEMENT sinhvien (masv,hoten,tuoi,dienthoai,diachi)>
<!-- du tat ca cac thong tin-->
<!-- | co 1 trong cac thong tin-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT masv (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hoten (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tuoi (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT dienthoai (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT diachi (#PCDATA)>

=== ManhHongPham/semester6_xml/session 1/Proj_5002_xml/src/Section1/Lophoc.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE lophoc SYSTEM "Lophoc.dtd">
<lophoc>       
    <sinhvien>
        <masv>2018452347</masv>
        <hoten>Nguyen Van Tuan</hoten>
        <tuoi>22</tuoi>
        <dienthoai>4782384723</dienthoai>
        <diachi>Hai phong</diachi>
    </sinhvien>     
    <sinhvien>
        <masv>2018452347</masv>
        <hoten>Nguyen Van Tuan</hoten>
        <tuoi>22</tuoi>
        <dienthoai>4782384723</dienthoai>
        <diachi>Hai phong</diachi>
    </sinhvien>      
</lophoc>
