=== ManhHongPham/semester6_xml/review_test1/Thuvien.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:complexType name="sach">
        <xs:sequence>
            <xs:element name="tensach">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:element>
            <xs:element name="theloai">
                <xs:simpleType>
                    <xs:restriction base="xs:string"/>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        
        <xs:attribute name="masach">
            <xs:simpleType>
                <xs:restriction base="xs:ID"></xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="sotrang">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="7"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="nhaxuatban">
        <xs:sequence>
            <xs:element name="tennhaxuatban">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="kim đồng"/>
                        <xs:enumeration value="giáo dục"/>
                        <xs:enumeration value="khoa học xã hội"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            
            <xs:element name="sach" type="sach" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        
        <xs:attribute name="MaNXB">
            <xs:simpleType>
                <xs:restriction base="xs:ID"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="TV">
        <xs:sequence>
            <xs:element name="nhaxuatban" type="nhaxuatban" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="TenTV">
            <xs:simpleType>
                <xs:restriction base="xs:string"/>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:element name="DS">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="TV" type="TV" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ManhHongPham/semester6_xml/review_test1/ThuVien.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ThuVien.xsl"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<DS
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Thuvien.xsd'>
    <TV TenTV="tạ quang bửu">
        <nhaxuatban MaNXB="a1">
            <tennhaxuatban>giáo dục</tennhaxuatban>
            <sach masach="b1" sotrang="200">
                <tensach>vì em đẹp lắm</tensach>
                <theloai>kinh dị</theloai>
            </sach>
            <sach masach="b2" sotrang="500">
                <tensach>em xinh lắm</tensach>
                <theloai>kinh dị</theloai>
            </sach>
        </nhaxuatban>
        <nhaxuatban MaNXB="a2">
            <tennhaxuatban>khoa học xã hội</tennhaxuatban>
            <sach masach="b3" sotrang="300">
                <tensach>hoa hồng</tensach>
                <theloai>viễn tưởng</theloai>
            </sach>
        </nhaxuatban>
    </TV>
    <TV TenTV="quốc gia">
        <nhaxuatban MaNXB="a3">
            <tennhaxuatban>giáo dục</tennhaxuatban>
            <sach masach="b4" sotrang="400">
                <tensach>kim hoa </tensach>
                <theloai>ngôn tình</theloai>
            </sach>
        </nhaxuatban>
    </TV>

</DS>
