=== ManhHongPham/semester6_xml/vidu/src/movie/movie.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT movies (movie+) >
<!ELEMENT movie (name,information,description)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST movie maphim ID #REQUIRED>
<!ELEMENT information (country,year,quality,audio,update,otherName,type)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT audio (#PCDATA)>
<!ELEMENT update (#PCDATA)>
<!ELEMENT otherName (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!--- PCDATA  Về cơ bản được sử dụng cho NGUYÊN NHÂN trong khi CDATA -->
 <!-- Được sử dụng cho các thuộc tính của XML, tức là ATTLIST -->

=== ManhHongPham/semester6_xml/vidu/src/movie/movie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies SYSTEM 'movie.dtd'>
<movies>
    <movie maphim="a11">
        <name>superman</name>
        <information>
            <country>USA</country>
            <year>2020</year>
            <quality>HD</quality>
            <audio>FULL</audio>
            <update>2020</update>
            <otherName>sieu anh hung</otherName>
            <type>action</type>
        
        </information>
        <description>phimhanh dong</description>
    </movie>
    <movie maphim="a12">
        <name>love</name>
        <information>
            <country>USA</country>
            <year>2019</year>
            <quality>HD</quality>
            <audio>FULL</audio>
            <update>2020</update>
            <otherName>sieu anh hung</otherName>
            <type>action</type>
        </information>
        <description>phimhanh dong</description>
    </movie>
</movies>
